---
AWSTemplateFormatVersion: "2010-09-09"

Description: CloudFormation Template to create a ec2 instance, Install jenkins and java.

#------------------------
#   METADATA
#------------------------

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Compute Configuration
        Parameters:
          - TemplateName
          - InstanceImageId
          - InstanceType

#------------------------
#   PARAMETERS
#------------------------

Parameters:
  TemplateName:
    Type: String
    Description: Enter the name of your resource you are creating.
    Default: jenkins-instance

  InstanceImageId:
    Type: String
    Default: ami-080e1f13689e07408
    AllowedValues: 
      - ami-080e1f13689e07408 # Ubuntu
    Description: Amazon Machine Image Id.

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.small
      - t2.medium
      - t2.large
    Description: Instance family and type.

#------------------------
#   RESOURCES
#------------------------

Resources:
  ## Our EC2 SSH Key
  JenkinsKeyName:
    Type: "AWS::EC2::KeyPair"
    Properties:
      KeyName: !Join ["-", [!Ref TemplateName, "key-pair"]]

  # Our EC2 security group
  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH, HTTP, and Additional Ports
      VpcId:
        Fn::ImportValue: !Sub JenkinsVPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
          IpProtocol: tcp
        - CidrIp: 0.0.0.0/0
          FromPort: 8080
          ToPort: 8080
          IpProtocol: tcp

  # Configuring ec2 Instance
  JenkinsEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref JenkinsKeyName
      ImageId: !Ref InstanceImageId
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !Ref JenkinsSecurityGroup
      SubnetId:
        Fn::ImportValue: !Sub PublicSubnet1
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install -y fontconfig openjdk-17-jre
          java -version

          # Add Jenkins repository key
          sudo wget -q -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian/jenkins.io-2023.key

          # Add Jenkins repository
          echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

          # Update package index
          sudo apt-get update

          # Install Jenkins
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --allow-unauthenticated jenkins

          # Start Jenkins service
          sudo systemctl start jenkins

          # Enable Jenkins service to start on boot
          sudo systemctl enable jenkins

      Tags:
        - Key: Name
          Value: !Sub ${TemplateName}
